# Generated by Django 3.2.9 on 2021-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_remove_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_width',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ImageField(null=True, upload_to='books/covers/%Y/%m/%d', width_field='cover_width'),
        ),
    ]
