# Generated by Django 3.2.9 on 2021-11-26 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20211126_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='covers',
            new_name='cover',
        ),
    ]
