# Generated by Django 3.2.9 on 2021-12-06 13:18

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='books/covers/%Y/%m/%d'),
        ),
    ]
